name: Manual E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        default: 'dev'
        type: environment

jobs:
  run-tests:
    name: Run E2E Tests
    # https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html#sample-github-action-runners-create-project
    # large = 15 GB memory, 8 vCPUs
    # 7.0 = Ubuntu 22.04
    runs-on: codebuild-ThorE2E-GHA-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node Modules
        run: yarn install

      - name: Start Network
        # Only start the network if we're not running against mainnet/ testnet
        if: ${{ inputs.environment == 'solo' || inputs.environment == 'default-private' }}
        run: |
          yarn docker:up

      - name: Run Tests
        run: yarn test:fast
        env:
          NODE_URLS: ${{ vars.NODE_URLS }}
          NETWORK_TYPE: ${{ vars.NETWORK_TYPE }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
