name: On Push

on:
  push:
    branches:
      - '*'

jobs:
  run-test:
    strategy:
      matrix:
        index: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    runs-on: ubuntu-latest
    steps:
      - name: Run Sleep and Test
        uses: ./.github/actions/sleep-and-test.yaml
        with:
          sleep_duration: ${{ format('{0}', 3 * matrix.index) }}
